# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf0d7f2eab999657eebf91fe5706286c0b1673f8c8fd4791162c410bd524d21e7e7166317be52e637127529ffc98e4a11c1f3f1f82c114f8be1e5304bbd1d977

test:
  secret_key_base: eb63662423bc66a5b054e34132d3ff82ef857454a6c4bbfeda0d23b5311ce44ede62a17ea68f41beb3b79e007b10bbaa23e80cda296cf3c936efe5eb48f5659c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
